name: Daily Check-in
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0-6' # Every day at 00:00
permissions:
  contents: write
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Cache Python packages and user data
        uses: actions/cache@v4
        with:
          path: |
            .venv
            $HOME/.config/getscipapers/ablesci/chrome_user_data
            $HOME/.config/getscipapers/wosonhj/chrome_user_data
              key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
              restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies if cache is missed
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Load credentials
        run: |
          source .venv/bin/activate
          bash .devcontainer/set-secrets.sh --apply-credentials-base64 "${{ secrets.CREDS }}"

      - name: Run daily check-in
        run: |
          source .venv/bin/activate
          getscipapers checkin all