name: Daily Check-in
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0-6' # Every day at 00:00
permissions:
  contents: write
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python packages
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Load credentials
        run: |
          bash .devcontainer/set-secrets.sh --apply-credentials-base64 "${{ secrets.CREDS }}"

      - name: Run daily check-in
        run: |
          getscipapers checkin all